// <auto-generated />
namespace AutoFin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addtablasrolesusuariospermisospropietarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtablasrolesusuariospermisospropietarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121806514_Add tablas roles, usuarios, permisos, propietarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
